version: '3'
services:
  trezor-user-env-unix:
    container_name: trezor-user-env.unix
    image: registry.gitlab.com/satoshilabs/trezor/trezor-user-env/trezor-user-env
    network_mode: "host"
    ports:
      - "9001:9001"
      - "21326:21326"
    environment:
      - DISPLAY=:0

  trezor-user-env-mac:
    container_name: trezor-user-env.mac
    image: registry.gitlab.com/satoshilabs/trezor/trezor-user-env/trezor-user-env
    ports:
      - "9001:9001"
      - "21326:21326"
      - "127.0.0.1:21325:21326" # macos needs proxy to override the "origin" of the trezord request
    environment:
      - DISPLAY=docker.for.mac.host.internal:0

  trezor-user-env-arm-mac:
    container_name: trezor-user-env-arm.mac
    image: trezor-user-env-arm.mac #this should be then replaced by image that is build by ci, for now "docker buildx build -t trezor-user-env-arm.mac . -f ./docker/arm-docker/Dockerfile --load"
    ports:
      - "9001:9001"
      - "21326:21326"
      - "127.0.0.1:21325:21326" # macos needs proxy to override the "origin" of the trezord request
    environment:
      - DISPLAY=docker.for.mac.host.internal:0
