name: build and push trezor-user-env master images

on:
  push:
    branches:
      - "master"
      - "m1-testing"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/vdovhanych/trezor-user-env:latest
            ghcr.io/vdovhanych/trezor-user-env:GITHUB_SHA
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/arm/
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/vdovhanych/trezor-user-env-arm:latest
            ghcr.io/vdovhanych/trezor-user-env-arm:GITHUB_SHA
